### PR TITLE
test perldoc output

### PR DESCRIPTION
**Pull request by hatorikibble**
just a small idea to test if perldoc can parse POD and produces the correct output

### CODE REVIEW

**Comment by mrallen1** [comment]
Great idea! 

However, because perldoc is included in the perl core, I am wary of using modules that aren't also part of core perl in any part of its Makefile. Is there a way to implement the test without using Test::Output? Perhaps by quoting some of it inline, or perhaps redirecting the perldoc output into a file and running a regex on its content?

Just kind of spitballing here as far as what might work best.

**Comment by hatorikibble** [comment]
Thanks for your comment! That makes sense, I'll try to figure something out

**Comment by hatorikibble** [comment]
So the tests now relies only on core modules. Also I tried to treat the path names as platform-neutral as possible, but I have no way to test this.

Can you use cpantesters.org without making an official release to run this on different operating systems?

**Comment by mrallen1** [comment]
Yes I can package and publish a test release

**Comment by mrallen1** [comment]
I will be publishing a new test release soon - within the next 2 days for CPANT purposes.

**Comment by hatorikibble** [comment]
Thanks!

**Comment by mrallen1** [comment]
OK. I released 3.25_01 to CPAN today. We'll see what kind of reports come back from CPANTs! Thanks again.

**Comment by hatorikibble** [comment]
Thanks for preparing the test release! But I just looked at reports e.g. http://www.cpantesters.org/cpan/report/3e8177a6-b77e-11e5-b156-f89cfbd2507e it seems the new test is not included?

**Comment by mrallen1** [comment]
Oh goodness, sorry. I forgot to update the MANIFEST in the release. That's been fixed and I just published 3.25_02

**Comment by mrallen1** [comment]
Pod-Perldoc-3.25_02:
- MSWin32-x86-multi-thread / 5.12.2:
  - FAIL http://www.cpantesters.org/cpan/report/88079e33-6bf6-1014-9f8a-baa0b3fb7a49

- MSWin32-x86-multi-thread / 5.16.1:
  - FAIL http://www.cpantesters.org/cpan/report/7cf1586a-6bfe-1014-b865-1126e968558f

- MSWin32-x86-multi-thread / 5.16.3:
  - FAIL http://www.cpantesters.org/cpan/report/2b77e9b9-6bfb-1014-b001-91668a526996

- MSWin32-x86-multi-thread-64int / 5.18.2:
  - FAIL http://www.cpantesters.org/cpan/report/46f36e42-6bf9-1014-a7cb-3fd68734c665

- MSWin32-x86-multi-thread-64int / 5.20.1:
  - FAIL http://www.cpantesters.org/cpan/report/b5cf87c1-6bf8-1014-be29-03a2c4c14f55

- MSWin32-x86-multi-thread-64int / 5.22.1:
  - FAIL http://www.cpantesters.org/cpan/report/97e4ce47-6bfe-1014-8caa-d1042b7077ee

- amd64-netbsd / 5.12.5:
  - FAIL http://www.cpantesters.org/cpan/report/9d140f06-b9fc-11e5-b0cc-3ecf8fb2e322

- x86_64-dragonfly / 5.20.2:
  - FAIL http://www.cpantesters.org/cpan/report/8815a336-ba14-11e5-85b6-0da0aef69d38

- x86_64-dragonfly / 5.20.3:
  - FAIL http://www.cpantesters.org/cpan/report/8963ae60-b9ae-11e5-85b6-0da0aef69d38

- x86_64-dragonfly-thread-multi / 5.20.2:
  - FAIL http://www.cpantesters.org/cpan/report/29004a3c-ba4a-11e5-85b6-0da0aef69d38

- x86_64-dragonfly-thread-multi / 5.20.3:
  - FAIL http://www.cpantesters.org/cpan/report/4087585e-b9e5-11e5-85b6-0da0aef69d38

**Comment by mrallen1** [comment]
Interesting - mostly windows and some BSD flavors.

**Comment by hatorikibble** [comment]
damn you windows ;-) Sorry but now I am stumped.. At the moment I don't have any windows box to test the errors. This changes when my paternity leave ends in April, then I could use the machines at work to investigate these issues further. The probölems with the BSD-flavours are of a different kind and my knowledge of BSD is rather limited..
So I am afraid I have to revisited this test at a later time..

Another possibility would be to skip this test via $^O in Windows and on the BSD<->perl combinations, but that's just a dirty workaround ;-)

**Comment by mrallen1** [comment]
Yeah I am wary of disabling the test just for WIndows / BSD. I think what I'm going to do is this: I'm going to push this test on to a new branch, and then revert master.  When/if you have time/interest to look at the test failures on Windows, we can revisit the branch.

Sound fair?

**Comment by mrallen1** [comment]
P.S. Congratulations on paternity leave. :)

**Comment by hatorikibble** [comment]
Thanks ;-)

The idea with the branch sounds good to me. I'm sorry that so far I caused more work for you than actual help, but at least it's an interesting learning opportunity for me.. ;-)

**Pull request merged**
